version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: docker_pour_tester_config_dev_dans_docker
    tty: true
    working_dir: /code
    volumes:
      - .:/code

  base:
    image: docker_base
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/ivm:/home/smith/code/
    tty: true

  dpvo:
    image: docker_dpvo
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true

  msdp:
    image: docker_msdp
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true

  droid:
    image: docker_droid
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true

  select:
    image: docker_select
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true

  dpvslam:
    image: docker_dpvslam
    network_mode: host
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    tty: true




  # tensorrt:
  #   image: docker_ivm_display
  #   network_mode: host
  #   runtime: nvidia
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   environment:
  #     - DISPLAY=$DISPLAY
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - .:/code
  #   tty: true
  #
  # appgpu:
  #   build: .
  #   network_mode: host
  #   runtime: nvidia
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  #   environment:
  #     - DISPLAY=$DISPLAY
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - .:/code
  #   tty: true
